// Shapes of the committed snapshot (web/public/data), produced by
// pipeline/services/snapshot.py. Keep in step with SCHEMA_VERSION there.

export interface SnapshotManifest {
  schema_version: string;
  generated_at: string;
  counts: Record<string, number>;
  runs?: { source: string; capability: string; finished_at: string | null; status: string }[];
}

/** standard = fitted on this trim; pack/option = available for this trim via a
 * named pack or option; none = not available; unknown = not captured. */
export type Tri = "standard" | "pack" | "option" | "none" | "unknown";

export interface RequirementCheck {
  passes: boolean;
  failures: string[];
  unknown: string[];
}

/** gone = the latest check did not find the offer; expired = past valid_to or
 * the source said so; otherwise the status the source implied when last seen. */
export type OfferState = "live" | "lead" | "derived" | "illustrative" | "campaign" | "expired" | "historical" | "gone";

export interface ObservationPoint {
  observed_at: string;
  /** Last time this exact state was confirmed; null when seen once. */
  confirmed_at?: string | null;
  present: boolean;
  source: string;
  monthly_payment?: number;
  vehicle_price?: number;
  apr?: number;
  gfv?: number;
  initial_rental?: number;
  monthly_rental?: number;
}

export interface Freshness {
  state: OfferState;
  /** Relative to manifest.generated_at. The UI recomputes age from last_seen_at. */
  stale: boolean;
  age_days: number | null;
  first_seen_at: string;
  last_seen_at: string | null;
  last_checked_at: string;
  observations: number;
  present: boolean;
  history: ObservationPoint[];
}

/** One used listing as used.json carries it (every listing ever seen; present = still on sale). */
export interface SnapshotUsed {
  listing_key: string;
  provider: string;
  source?: string | null;
  make?: string | null;
  make_slug?: string | null;
  model?: string | null;
  model_slug?: string | null;
  /** make/model slugs, the subject of the model's used series (added at load). */
  model_key?: string;
  car_id?: string | null;
  price_gbp: number | null;
  year: number | null;
  mileage: number | null;
  present: boolean;
  first_seen_at: string;
  last_seen_at: string;
  derivative?: string | null;
  town?: string | null;
  url?: string | null;
  image_url?: string | null;
  vrm?: string | null;
}

/** What only the car page reads, fetched on demand (details.json, keyed by car id). */
export interface CarDetails {
  id: string;
  specs: CarSpecSummary[];
  spec_check: { rows: SpecCheckRow[]; disagreements: number };
  /** The seed requirements' verdict at export (the pipeline's deal table); the app does not read it. */
  requirement_check: RequirementCheck;
  /** Where each resolved field came from (services/claims.py); absent for a hand-curated car's own reading. */
  field_sources?: Record<string, string> | null;
  /** Fields the strongest sources disagree on, with both sides; the field stays unknown. */
  disagreements?: Record<string, string[]> | null;
  /** A named, maker or configured claim a stronger one set aside. */
  overruled?: Record<string, string[]> | null;
}

/** One offer observation span as sightings.json carries it: a price one source
 * showed for one derivative over the days it stayed the same, with the payload
 * the browser costs (lib/model). */
export interface SnapshotSighting {
  key: string;
  car_id: string;
  /** make/model slugs. */
  model: string;
  route: FinanceType;
  /** The site (a source id; data.json names it), and the provider that read it. */
  source: string;
  provider: string;
  status: string;
  seller: string | null;
  from: string;
  to: string;
  present: boolean;
  deal: Record<string, unknown>;
}

/** One used listing's asking-price span (used_spans.json). */
export interface SnapshotUsedSpan {
  key: string;
  source: string;
  model: string;
  car_id: string | null;
  year: number | null;
  price: number | null;
  mileage: number | null;
  vrm: string | null;
  town: string | null;
  from: string;
  to: string;
  present: boolean;
}

export interface SnapshotCar {
  /** make/model slugs: the subject of the model's used spans. */
  model_key?: string;
  id: string;
  /** How many spec rows describe this car (details.json has them). */
  spec_count?: number;
  /** The derivative's CAP name as Carwow's model page prints it, brackets included. */
  cap_name?: string;
  /** Canonical equipment flags merged from the car's spec rows: standard beats option beats unlisted. */
  flags?: Record<string, FlagState>;
  make: string;
  model: string;
  trim: string;
  /** true = generated by the pipeline from a scraped source (every derivative
   * nobody curated by hand); absent = hand-curated in data/seed/cars.json. */
  auto?: boolean;
  /** For generated cars: 'spec' (from the Carwow specification page) or 'stub'
   * (only a deals page ever printed it). */
  source_kind?: "spec" | "stub";
  variant?: string;
  cap_id?: string;
  make_slug?: string;
  model_slug?: string;
  version_date?: string | null;
  packs?: string[];
  model_year?: number | null;
  used?: boolean;
  fuel?: string;
  body?: string;
  seats?: number | null;
  battery_kwh?: number | null;
  wltp_range_mi?: number | null;
  real_range_mi?: number | null;
  power_hp?: number | null;
  architecture_v?: number | null;
  dc_peak_kw?: number | null;
  /** Average charging power over a 10-80% rapid charge (EV Database). */
  dc_avg_kw?: number | null;
  dc_10_80_min?: number | null;
  ac_kw?: number | null;
  top_speed_mph?: number | null;
  weight_kg?: number | null;
  tow_kg?: number | null;
  evdb_url?: string | null;
  battery_usable_kwh?: number | null;
  battery_chemistry?: string | null;
  real_range_cold_mi?: number | null;
  real_range_mild_mi?: number | null;
  motorway_range_cold_mi?: number | null;
  motorway_range_mild_mi?: number | null;
  power_kw?: number | null;
  torque_lbft?: number | null;
  drive?: string | null;
  charge_port?: string | null;
  v2l_kw?: number | null;
  isofix_seats?: number | null;
  doors?: number | null;
  frunk_l?: number | null;
  wheelbase_m?: number | null;
  width_mirrors_mm?: number | null;
  gvwr_kg?: number | null;
  payload_kg?: number | null;
  roof_load_kg?: number | null;
  roof_rails?: boolean | null;
  tow_unbraked_kg?: number | null;
  /** The wheel size fitted as standard, inches. */
  wheel_in?: number | null;
  /** Other sizes the configurator offers: '19", 20"'. */
  wheel_options?: string | null;
  segment?: string | null;
  platform?: string | null;
  ncap_stars?: number | null;
  ncap_adult_pct?: number | null;
  ncap_child_pct?: number | null;
  ncap_vru_pct?: number | null;
  ncap_assist_pct?: number | null;
  ncap_year?: number | null;
  warranty_years?: number | null;
  warranty_miles?: number | null;
  zero_to_62_s?: number | null;
  length_mm?: number | null;
  width_mm?: number | null;
  height_mm?: number | null;
  turning_circle_m?: number | null;
  boot_l?: number | null;
  boot_max_l?: number | null;
  boot_notes?: string;
  efficiency_mi_kwh?: number | null;
  insurance_group?: string | null;
  heat_pump?: Tri;
  internal_v2l?: Tri;
  external_v2l?: Tri;
  packs_required?: Record<string, string> | null;
  pack_prices_gbp?: Record<string, number> | null;
  powered_sliding_doors?: number | null;
  memory_seats?: boolean;
  glass_roof?: boolean;
  heated_seats?: boolean;
  ventilated_seats?: boolean;
  camera_360?: boolean;
  list_price_gbp?: number | null;
  list_price_breakdown?: Record<string, number>;
  grant_gbp?: number | null;
  used_from_gbp?: number | null;
  expensive_car_supplement?: boolean;
  notes?: string;
  verification?: string;
  image_url?: string | null;
  /** Committed photo path (prefix with the base path) or image_url, resolved at export. */
  image?: string | null;
  picks: HouseholdPick[];
}

export interface UsedListing {
  listing_key: string;
  price_gbp: number;
  year: number | null;
  mileage: number | null;
  derivative: string | null;
  town: string | null;
  url: string | null;
  image_url?: string | null;
  age_days?: number | null;
  /** Which site lists it; 'sources' names every site when the same car is on more than one. */
  source?: string | null;
  sources?: string[] | null;
}

export interface HouseholdPick {
  who: string;
  verdict: "want" | "maybe" | "no" | "control" | string;
  note?: string | null;
}

export type FinanceType = "pcp" | "pch" | "cash" | "campaign";
/** A route on the true-monthly footing: the three finance types plus buying used. */
export type Route = "pcp" | "pch" | "cash" | "used";

export interface DealMetrics {
  skipped?: string;
  /** Every route on one footing: present cost at the savings rate, expected end value
   * credited back, spread as an annuity over the agreement. floor = end value at the GFV. */
  true_monthly?: number | null;
  true_monthly_floor?: number | null;
  pv_cost?: number | null;
  expected_value_at_end?: number | null;
  /** used-market (the model's stock at that age), gfv-grown (the lender's floor at the savings rate), assumption */
  residual_source?: string;
  expected_equity?: number | null;
  horizon_months?: number | null;
  /** A campaign (terms only, nothing to cost) keeps its APR for the table. */
  apr?: number | null;
  // pcp
  list_price?: number | null;
  vehicle_price?: number;
  manufacturer_contribution?: number;
  customer_deposit?: number;
  amount_of_credit?: number;
  num_payments?: number;
  term_months?: number;
  monthly_payment?: number;
  apr_stated?: number | null;
  apr_implied?: number | null;
  gfv?: number;
  gfv_pct_of_list?: number | null;
  gfv_pct_of_price?: number | null;
  paid_if_handed_back?: number;
  paid_if_bought?: number;
  cost_of_credit?: number;
  finance_vs_own_cash_price?: number;
  effective_monthly_hand_back?: number;
  monthly_at_0pct_same_gfv?: number;
  interest_per_month?: number;
  derived_fields?: string[];
  best_cash_price?: number;
  best_cash_deal_id?: string;
  acquisition_penalty_vs_cash?: number;
  funding_premium_vs_cash?: number;
  effective_rate_vs_cash?: number | null;
  // pch
  initial_rental?: number;
  monthly_rental?: number;
  num_rentals?: number;
  fees?: number;
  total_cost?: number;
  effective_monthly?: number;
  annual_mileage?: number | null;
  // cash
  discount_vs_list?: number | null;
}

export interface SnapshotOffer {
  id: string;
  car_id: string;
  provider: string;
  freshness: Freshness;
  captured_at: string;
  deal_date?: string;
  finance_type: FinanceType;
  status: string;
  verification?: string;
  source?: string;
  source_url?: string;
  source_ref?: string;
  dealer?: string;
  valid_from?: string;
  valid_to?: string;
  list_price?: number | null;
  vehicle_price?: number | null;
  dealer_discount?: number | null;
  grant_gbp?: number | null;
  saving_stated?: number | null;
  manufacturer_contribution?: number | null;
  customer_deposit?: number | null;
  amount_of_credit?: number | null;
  term_months?: number | null;
  num_payments?: number | null;
  first_payment?: number | null;
  monthly_payment?: number | null;
  apr?: number | null;
  fixed_rate_pa?: number | null;
  gfv?: number | null;
  total_payable_stated?: number | null;
  cost_of_credit_stated?: number | null;
  annual_mileage?: number | null;
  excess_mileage_ppm?: number | null;
  fees_gbp?: number | null;
  profile?: string;
  initial_rental?: number | null;
  num_rentals?: number | null;
  monthly_rental?: number | null;
  total_stated?: number | null;
  mileage?: number | null;
  warranty_remaining?: string;
  notes?: string;
  num_payments_stated?: number | null;
  condition?: string;
  location?: string | null;
  metrics: DealMetrics;
  /** The figure the cards rank by (over the reader's horizon or the deal's own term), and the deal's own-term figure. */
  comparable?: { true_monthly: number | null; horizon_months: number; at_horizon: string; own_true_monthly: number | null; own_horizon_months: number; end_value: number | null } | null;
}

/** An offer as the browser derives it from its spans (lib/model/offers.ts): the
 * latest state, its freshness, and the normalisation under the reader's basis. */
export type SnapshotDeal = SnapshotOffer;

export interface RunRow {
  id: number;
  source: string;
  capability: string;
  target: string;
  started_at: string;
  finished_at: string | null;
  status: string;
  artifacts: number;
  records: number;
  unmapped: number;
  errors?: number;
}

export interface UnmappedTrim {
  source: string;
  source_key: string;
  label: string | null;
  example_url: string | null;
  first_seen_at: string;
  last_seen_at: string;
  status?: "unmapped" | "conflict";
  method?: string | null;
  evidence?: Record<string, unknown> | null;
}

export interface DataPage {
  generated_at: string;
  stale_days: number;
  flag_labels?: Record<string, string>;
  providers: {
    name: string;
    live?: boolean;
    description?: string;
    source?: string;
    capabilities: { name: string; kinds: string[]; parser_version: string }[];
  }[];
  runs: RunRow[];
  unmapped_trims: UnmappedTrim[];
  offer_states: Record<string, number>;
  counts: Record<string, number>;
  /** Source id → display name (several providers read the same site). */
  sources?: Record<string, string>;
  /** How resolved trim-map rows were resolved: manual, cap-id, rrp, bracket, ... */
  resolution_methods?: Record<string, number>;
}

export interface RequirementRule {
  id: string;
  label: string;
  /** A short name for a card badge; label when absent. */
  short?: string;
  field?: string;
  op?: string;
  value?: unknown;
  weight?: number;
  direction?: string;
  applies_to?: string;
  /** false switches the rule off without deleting it (the reader's copy only). */
  enabled?: boolean;
  [k: string]: unknown;
}

export interface Requirements {
  as_of: string;
  household?: Record<string, unknown>;
  quoting_basis?: Record<string, unknown>;
  budget?: Record<string, unknown>;
  hard: RequirementRule[];
  preferences: RequirementRule[];
  wants: RequirementRule[];
  finance_posture?: Record<string, unknown>;
  context?: Record<string, unknown>;
  [k: string]: unknown;
}


/** standard = fitted; pack = available through a named pack (packs_required says which, pack_prices_gbp what it costs);
 * option = available on its own; none = not available; null / absent = no source says. */
export type FlagState = "standard" | "pack" | "option" | "none" | null;

/** One scraped variant: a Carwow CAP derivative or a Kia grade × powertrain (× seats). */
export interface SnapshotSpec {
  spec_key: string;
  provider: string;
  source: string;
  source_url: string;
  observed_at: string;
  make: string;
  model: string;
  model_slug: string;
  trim: string;
  variant: string;
  engine?: string;
  powertrain?: string;
  cap_id?: string;
  version_date?: string;
  model_year_hint?: string;
  seats?: number | null;
  car_id: string | null;
  rrp?: number | null;
  carwow_price?: number | null;
  image_url?: string | null;
  description?: string | null;
  features: string[];
  options: string[];
  flags: Record<string, FlagState>;
  numbers: Record<string, number | string | null>;
  first_seen_at: string;
  last_seen_at: string;
  changed_at: string | null;
}

export interface CarSpecSummary {
  spec_key: string;
  provider: string;
  variant: string | null;
  flags: Record<string, FlagState> | null;
  features: number;
  options: number;
  numbers: Record<string, number | string | null> | null;
  last_seen_at: string | null;
}

export interface SpecCheckRow {
  field: string;
  label: string;
  hand: string | null;
  source: string;
  seen: FlagState;
  verdict: string;
  spec_key: string;
}

/** models.json: the catalogue of every electric model Carwow lists. */
export interface SnapshotModel {
  slug: string;
  make: string;
  model: string;
  make_name: string | null;
  model_name: string | null;
  has_deals: boolean;
  has_specs: boolean;
  first_seen_at: string;
  last_seen_at: string;
  derivatives: number;
  cars: number;
  priced: number;
  used?: number;
}
