// After `next build`: write out/sw.js, a service worker that keeps the built app
// (every page, its RSC payloads, scripts, styles and icons) in the browser's cache so
// the site opens and navigates offline. The snapshot's data files are left out: the app
// stores the data in IndexedDB itself (src/lib/db.ts). The cache is named after a hash
// of the files, so each deploy installs a fresh copy and drops the previous one.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = fileURLToPath(new URL("../out/", import.meta.url));

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const skip = (rel) => rel === "sw.js" || rel === "404.html" || rel === ".nojekyll" || (rel.startsWith("data/") && rel.endsWith(".json")) || rel.startsWith("images/");
const files = walk(OUT).map((p) => relative(OUT, p).split(sep).join("/")).filter((rel) => !skip(rel)).sort();
const hash = createHash("sha256");
for (const rel of files) hash.update(rel).update(readFileSync(join(OUT, rel)));
const version = hash.digest("hex").slice(0, 12);

const sw = `// Generated by web/scripts/build-sw.mjs at build time; do not edit.
const VERSION = ${JSON.stringify(version)};
const FILES = ${JSON.stringify(files)};
const SHELL = "shell-" + VERSION;
const IMAGES = "images";
const SCOPE = self.registration.scope;               // ends with "/": the site's base path
const BASE = new URL(SCOPE).pathname;
const at = (rel) => new URL(rel, SCOPE).href;

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    await cache.addAll(FILES.map(at));
    // Each page under its directory address too (/cars/ as well as /cars/index.html).
    for (const rel of FILES.filter((f) => f === "index.html" || f.endsWith("/index.html"))) {
      const res = await cache.match(at(rel));
      if (res) await cache.put(at(rel.slice(0, -"index.html".length)), res.clone());
    }
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) if (key.startsWith("shell-") && key !== SHELL) await caches.delete(key);
    await self.clients.claim();
  })());
});

async function cacheFirst(request, name) {
  const cache = await caches.open(name);
  const hit = await cache.match(request);
  if (hit) return hit;
  const res = await fetch(request);
  if (res.ok) cache.put(request, res.clone());
  return res;
}

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE)) return;
  const rel = url.pathname.slice(BASE.length);
  if (rel === "sw.js" || (rel.startsWith("data/") && rel.endsWith(".json"))) return;   // the snapshot lives in IndexedDB
  if (rel.startsWith("images/")) { event.respondWith(cacheFirst(request, IMAGES)); return; }
  event.respondWith((async () => {
    const cache = await caches.open(SHELL);
    let hit = await cache.match(request, { ignoreSearch: true });
    if (!hit && request.mode === "navigate") {
      const dir = url.pathname.endsWith("/") ? url.pathname : url.pathname + "/";
      hit = (await cache.match(new URL(dir, url.origin).href)) || (await cache.match(SCOPE));
    }
    return hit || fetch(request);
  })());
});
`;
writeFileSync(join(OUT, "sw.js"), sw);
console.log(`sw.js: ${files.length} files precached, version ${version}`);
